
version: "3.1"

services:
  database:
    build: 
       context: ./database
    image: ddev_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB: ddev
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password

  apiserver:
    build:
       context: api
       dockerfile: Dockerfile.api
    image: ddev_api
    volumes:
      - ./api:/usr/src/ddev
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - back-tier
    secrets:
      - postgres_password

  watcher:
    build: 
      context: api
      dockerfile: Dockerfile.api
    volumes:
      - ./api:/usr/src/ddev
    command: mvn fizzed-watcher:run
    networks:
      - back-tier

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
    
networks:
  front-tier:
  back-tier: