version: "3.1"

services:
  database:
    image: pets-db:1.0
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB: ddev
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password

  api:
    image: pets-api:1.0
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password

  ui:
    build:
      context: ui
      dockerfile: Dockerfile-dev
    image: ddev_ui
    volumes:
      - ./ui/src:/app/src
      - ./ui/package.json:/app/package.json
    ports:
      - "3000:3000"
    networks:
      - front-tier

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password

networks:
  front-tier:
  back-tier: