FROM node:8-alpine

# This is only needed during development
# to auto-reload the app on src change
RUN npm install -g nodemon 

RUN mkdir /app
WORKDIR /app
COPY package.json /app/
RUN npm install
COPY ./src /app/src
EXPOSE 3000
CMD nodemon src/server.js -e html,js 0.0.0.0 3000